#!/bin/sh

. /lib/lsb/init-functions

case "$1" in
	start)
		log_info_msg "Remounting root file system in read-only mode..."
		mount -n -o remount,ro / >/dev/null
		evaluate_retval

		;;

	restart)
		$0 start
		;;

	*)
		echo "Usage: ${0} {start|restart}"
		exit 1
		;;
esac

exit 0

